### ISSUE TITLE
验证用户名和密码的逻辑

### ISSUE THREAD

**Issue by zhongjq** [yansongda/laravel-api#1]
亲，你这个扩展没看到与username和password的整合呢。 passport里面那个password模式是有这个代码逻辑的，你这个怎么搞呢

**Comment by yansongda** [comment]
这个包定位是多用户多应用的 API 包，也就是说，不存在 password 模式。

**是通过应用的  app_id 和 app_secret 进行认证获取 access_token ,通过 access_token 进行鉴权！**

感谢支持

**Comment by zhongjq** [comment]
明白，那就是不是给用户认证使用的，谢谢

**Comment by yansongda** [comment]
是的。认证用户可以通过相应页面新建相关开发应用，获取到 app_id 和 app_secret 进行鉴权。
